<a href="https://colab.research.google.com/github/shubham-dalmia/sds-tasks/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Print the numpy version and the configuration

In [2]:
print(np.__version__)
print(np.show_config)

1.19.5
<function show at 0x7fb7d9d9e680>


3. Create a null vector of size 10

In [3]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array 

In [4]:
arr=np.array([1,2,3,4,5])
print(arr.nbytes)

40


5. How to get the documentation of the numpy add function from the command line?

In [5]:
print(np.info(np.add))

None


6. Create a null vector of size 10 but the fifth value which is 1 

In [6]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49

In [7]:
b=np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)

In [8]:
b=b[::-1]
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
np.matrix(np.arange(9).reshape((3,3)))

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [10]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

11. Create a 3x3 identity matrix

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values

In [12]:
np.random.random((3,3,3))

array([[[0.68942369, 0.18318677, 0.39583771],
        [0.31700502, 0.60409426, 0.86554653],
        [0.38934822, 0.30051216, 0.43156321]],

       [[0.96208238, 0.10938986, 0.37377299],
        [0.68917627, 0.10941888, 0.6915557 ],
        [0.98719696, 0.99626732, 0.94663848]],

       [[0.36176332, 0.64270531, 0.91615218],
        [0.4346429 , 0.74819913, 0.76915028],
        [0.88165412, 0.53754858, 0.12029533]]])

13. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
d=np.random.random((10,10))
print(d)
print(d.min())
print(d.max())

[[0.86256087 0.82257505 0.42385635 0.0959995  0.49332644 0.98687554
  0.54667736 0.85443848 0.4148213  0.97824845]
 [0.7463088  0.71082905 0.11159725 0.27031679 0.83522219 0.55301061
  0.98755046 0.85662517 0.12392008 0.69709329]
 [0.08866327 0.68608001 0.12145526 0.26941829 0.55161586 0.25188063
  0.281082   0.28925267 0.49835597 0.29757086]
 [0.19698071 0.12157515 0.32019363 0.8121472  0.29548218 0.28544225
  0.73238705 0.92146534 0.94093449 0.69553179]
 [0.93949073 0.83201431 0.56708346 0.54739955 0.44594591 0.55933353
  0.26068855 0.25817774 0.8042561  0.22894735]
 [0.52669327 0.84915812 0.93650442 0.89653673 0.00245399 0.27197554
  0.5165206  0.45614991 0.90921658 0.90884196]
 [0.7671988  0.84220901 0.53822008 0.32757061 0.58301174 0.82518365
  0.36910882 0.39261215 0.41243249 0.6735715 ]
 [0.31507843 0.08791196 0.11177386 0.68643488 0.39640082 0.58687923
  0.51489113 0.20311043 0.6721267  0.13946521]
 [0.21206942 0.90855719 0.02697234 0.07826872 0.38529841 0.64298445
  0.55606702

14. Create a random vector of size 30 and find the mean value

In [14]:
e=np.random.random(30)
print(e.size)
print(e)
print(e.mean())

30
[0.55760169 0.58346544 0.40813489 0.71070357 0.45875809 0.41520285
 0.08910801 0.93581533 0.69363646 0.50216689 0.87031563 0.74770414
 0.13295915 0.04001612 0.56951911 0.6180316  0.70198016 0.85198425
 0.24590386 0.33111125 0.77645724 0.76882223 0.61341714 0.18578252
 0.57133326 0.61429009 0.1999935  0.67030671 0.86929055 0.03485312]
0.525622161015376


15. Create a 2d array with 1 on the border and 0 inside

In [15]:
f=np.ones((3,3))
f[1:-1,1:-1]=0
print(f)


[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array?

In [16]:
g=np.ones((5,5))
print(np.pad(g, pad_width=1, mode='constant',
               constant_values=0))


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [18]:
h=np.zeros((5,5))
for i in range(4):
  h[i+1,i]=i+1
print(h)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [19]:
i=np.zeros((8,8))
i[0:8:2,0:8:2]=1
i[1:9:2,1:9:2]=1
print(i)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


20.Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th **element**

In [20]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


21. Create a checkerboard 8x8 matrix using the tile function

In [21]:
arr=np.array([[1,0],[0,1]])
brr=np.tile(arr,(4,4))
print(brr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


22. Normalize a 5x5 random matrix

In [22]:
j=np.random.random((5,5))
print(j)
max=j.max()
min=j.min()
j=(j-min)/(max-min)
print(j)

[[0.03701512 0.57091578 0.53481707 0.47366542 0.87875786]
 [0.16509701 0.76040974 0.63726475 0.34800586 0.13754738]
 [0.33813019 0.27340579 0.60340911 0.39882968 0.93157307]
 [0.10465377 0.15132163 0.73793215 0.81108101 0.32576181]
 [0.0215033  0.88063055 0.70302455 0.3816121  0.25976946]]
[[0.01704464 0.60370369 0.56403782 0.49684335 0.94196576]
 [0.15778319 0.81192285 0.67660906 0.35876651 0.12751119]
 [0.34791497 0.27679469 0.6394079  0.41461258 1.        ]
 [0.09136714 0.14264656 0.7872241  0.86760129 0.33432438]
 [0.         0.9440235  0.74886704 0.39569362 0.26181087]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [23]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [24]:
arr1=np.full((5,3),4)
arr2=np.full((3,2),2)
print(np.matmul(arr1,arr2))

[[24 24]
 [24 24]
 [24 24]
 [24 24]
 [24 24]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [25]:
arr = np.arange(15)
print(arr)
print("\n")
arr[(arr >= 3) & (arr<= 8)] = 0
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


[ 0  1  2  0  0  0  0  0  0  9 10 11 12 13 14]


26. What is the output of the following script?

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27.Consider an integer vector Z, which of these expressions are legal?

In [33]:
Z=3
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

27
4
False
3j
3.0
False


28. What are the result of the following expressions?

In [36]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


29. How to round away from zero a float array ?

In [46]:
k=np.array([0.9,1.4,2.5,3.5,4.0,5.0199])
print(np.round(k,0))

[1. 1. 2. 4. 4. 5.]


30. How to find common values between two arrays? 

In [51]:
l=np.arange((7))
m=np.arange((10))
print(np.intersect1d(l,m))

[0 1 2 3 4 5 6]


31. How to ignore all numpy warnings (not recommended)?

In [52]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

32. Is the following expressions true?

In [56]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
#print(np.sqrt(-1))
#print(np.emath.sqrt(-1))

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


33. How to get the dates of yesterday, today and tomorrow?

In [63]:
print("TODAY     = ", np.datetime64('today', 'D'))
print("YESTERDAY = ", np.datetime64('today', 'D') - np.timedelta64(1, 'D'))
print("TOMORROW  = ",np.datetime64('today', 'D') + np.timedelta64(1, 'D'))

TODAY     =  2021-09-16
YESTERDAY =  2021-09-15
TOMORROW  =  2021-09-17
